# Generated by Django 3.2.16 on 2022-10-11 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jukugo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jukugo', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='入力')),
                ('pre_jukugo', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='前の熟語')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game', to='account.specialuser', verbose_name='アカウント名')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
